salesforce/rules_spring

tools/springboot/BUILD, tools/springboot/tests/verify_conflict_test.py, tools/springboot/whitelist.txt
=> Added a test and updated the whitelist

tools/springboot/springboot.bzl
This reverts commit cfa3b07eb2768d9c58485023d35c0169f9842ec0.
=> Revert "Add support for non-java dependency in SpringBoot rule"

tools/springboot/springboot.bzl
If you're a good person and have your dependencies under control, you shouldn't need this. We aren't good people.
This allows you to exclude by label a set of jars from appearing in the Springboot jar. We need this to not have multiple versions of log4j (because they decided to rename the package) coming from our maven transitive dependencies.
=> Add optional exclusion list to springboot rules

tools/springboot/allowlist.txt
This is a clean up of allowlist
=> allowlist.txt reduced to well known proto jar collisions

samples/helloworld/BUILD, tools/springboot/BUILD, tools/springboot/check_dupe_classes.py, tools/springboot/springboot.bzl, tools/springboot/springboot_pkg.sh
more refinements of the dupe check rule invocation
=> invoke dupe checker directly from Bazel, not through genrule

tools/springboot/check_dupe_classes.py, tools/springboot/springboot.bzl
fix case where allowlist is not passed in
=> fix bug in new dupe checker

tools/springboot/springboot_pkg.sh
Fixes Issue #61 
When writing the dependencies in the Spring Boot jar, previously there was extraneous clutter in the subdirectories used to contain each dep. This PR reduces the clutter.
For internal libs from the Bazel workspace, the path will now look like this:
BOOT-INF/lib/samples/helloworld/libs/lib1/liblib1.jar
For maven_install sourced deps, the path will now look like this:
BOOT-INF/lib/javax/websocket/javax.websocket-client-api/1.0/javax.websocket-client-api-1.0.jar
Previously there were path tokens like: 
BOOT-INF/lib/bazel-out/darwin-fastbuild/bin/external/maven/v1/https/repo.acme.com/nexus/content/groups/public/com/fasterxml/jackson/core/jackson-annotations/2.10.5/jackson-annotations-2.10.5.jar
=> write jars into BOOT-INF/lib with less path clutter

tools/springboot/springboot_pkg.sh
this resolves an issue in PR #75
=> small fix to packaging script following dep ordering PR

README.md, springboot/README.md, springboot/springboot.bzl, springboot/unwanted_classes.md, tools/get_github_stats_downloads.py
=> finalize github repo rename to rules_spring

springboot/springboot.bzl, springboot/springboot_pkg.sh, springboot/write_manifest.sh
This fixes #119 and makes it sensitive to the "underscore" version of the spring boot dependency, another part missing from #111.
@plaird Sorry for the direct jar use.
=> Use jar tool from toolchain

examples/demoapp/custom_bazelrun_script.sh, makerelease.sh, springboot/default_bazelrun_script.sh, springboot/springboot.bzl, springboot/write_bazelrun_env.sh
=> fix for use case of springboot rule in root of workspace

springboot/write_manifest.sh
=> Fix build failure if java_library has no META-INF/MANIFEST.MF

springboot/write_gitinfo_properties.sh
=> fix write_gitinfo_properties.sh

makerelease.sh, springboot/springboot.bzl
=> pass tags attr to all subrules

MODULE.bazel
=> add bzlmod MODULE.bazel

springboot/README.md, springboot/springboot_pkg.sh, springboot/src/main/java/com/salesforce/rulesspring/cli/SpringBootInspector.java
=> minor updates

examples/demoapp/BUILD, examples/demoapp/author.txt, examples/demoapp/info.txt, springboot/BUILD, springboot/addin_end.txt, springboot/springboot.bzl, springboot/springboot_doc.md, springboot/springboot_pkg.sh
=> Implement addins feature

README.md, makerelease.sh
=> release of 2.2.2

README.md, makerelease.sh
2.2.4 was released. Making post-release updates
=> post 2.2.4 release updates

springboot/check_dupe_classes.py
Just saw this locally on my machine when I ran out of disk space during a bazel build.
=> handle cases of corrupt jar files

springboot/springboot_pkg.sh
Attempt at solving https://github.com/salesforce/rules_spring/issues/176 
This is a bit naive, but it seems to work as expected for us.
The examples and tests in rules_spring runs as well
=> Include META-INF/services folder

examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java, makerelease.sh, springboot/cli.md, springboot/springboot.bzl, springboot/springboot_pkg.sh, springboot/src/main/java/com/salesforce/rulesspring/index/IndexOfFiles.java
This PR fixes a few spelling errors.
=> Fix spelling

MODULE.bazel, tools/python_interpreter/BUILD
For https://github.com/salesforce/rules_spring/issues/194
=> Captive python documentation fix

examples/demoapp/libs/lib1/BUILD, examples/demoapp/libs/lib2/BUILD, examples/helloworld/libs/lib1/BUILD, examples/helloworld/libs/lib2/BUILD
Apply buildifier on a few build files
=> Apply buildifier

MODULE.bazel, README.md, springboot/README.md, springboot/import_bundles/README.md, springboot/unwanted_classes.md, tools/buildstamp/README.md
- doc updates for 2.4.1 release
- MODULE updates
- other doc clarifications
=> release 2.4.1 docs

springboot/springboot.bzl
=> Fix launcher to not require --legacy_external_runfiles

MODULE.bazel
=> Remove python toolchain version from bzldmo

springboot/springboot.bzl
Solution for #139. Allows multiple springboot() targets in the same BUILD file.
=> support multiple springboot targets in a BUILD file

examples/demoapp/BUILD
example of the two target feature in 2.5.2
=> add an example second target

springboot/springboot.bzl
=> allow multiple bazelrun datafiles

examples/demoapp/custom_bazelrun_script.sh, springboot/bazelrun.md, springboot/default_bazelrun_script.sh
=> add support for JAVABIN

springboot/springboot.bzl, springboot/springboot_doc.md
Solves #250, see comment there for more details.
=> switch to host java for jartools, to support multi-arch

springboot/README.md, springboot/springboot_pkg.sh
=> Fix case of debug flag

examples/demoapp/BUILD, examples/demoapp/libs/lib3_neverlink/BUILD, examples/demoapp/libs/lib3_neverlink/README.md, examples/demoapp/libs/lib3_neverlink/src/main/java/com/bazel/demo/IntentionalDupedClass.java, examples/demoapp/libs/lib3_neverlink/src/test/java/com/bazel/demo/IntentionalDupedClassTest.java
It turns out, it just works. Test case for #157
=> add neverlink example to demoapp

README.md, springboot/deps_filter_rules/README.md, springboot/unwanted_classes.md
=> release 2.6.3 docs
