tools/springboot/springboot_pkg.sh, tools/springboot/write_manifest.sh
The internal repo we have did not transition to maven_install as we expected due to some issue. But I was finally able to build a test workspace and test the changes suggested by @thundergolfer and @dan-cohn in issue #13 
The fixes are backwards compatible with maven_jar, and thus can be merged to master. I have some additional work (import_bundles, docs) to fully support maven_install, but the core rule logic is fixed.
=> fixes for maven_install

tools/springboot/springboot.bzl
With the latest bazel version 2.0.0 the spring_boot rule can no longer be executed because of the following error message:
```
ERROR: /opt/tgs_workspace_bazel/apex.gaming.server.tablegame-boot/BUILD:84:1: in _springboot_rule rule //apex.gaming.server.tablegame-boot:apex-gaming-server-tablegame-boot: 
Traceback (most recent call last):
File "/opt/tgs_workspace_bazel/apex.gaming.server.tablegame-boot/BUILD", line 84
_springboot_rule(name = 'apex-gaming-server-tablegame-boot')
File "/opt/tgs_workspace_bazel/tools/springboot/springboot.bzl", line 88, in _springboot_rule_impl
outs += ctx.attr.app_compile_rule.files
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily …
```
=> Changed outs to new transitive depset instead of old union operator

tools/springboot/springboot.bzl, tools/springboot/springboot_pkg.sh, tools/springboot/write_manifest.sh
This is a big change. This PR causes the rule to use Bazel's singlejar to package the final spring boot jar, instead of the jar command. This solves issue #19 which wants to have a hermetic output. 
We have been running with this new packaging approach internally at Salesforce for 4 days and haven't seen any issues in CI or in actual deployments. If this breaks you after we merge to master, please post back asap. I decided NOT to make this feature opt-in, it is enabled for all.
=> singlejar implementation

tools/springboot/verify_conflict.py
running with --curses=no, realized that we were writing a log message that is unnecessary almost all the time
=> eliminate unnecessary log message

tools/springboot/springboot.bzl
full_compile_jars includes the jars that are included in transitive runtime jars. There was a case where protobuf jars would be missed if in exclude list.
=> Fix exclude to use full_compile_jars

.gitignore, WORKSPACE, samples/helloworld/BUILD, samples/helloworld/helloworld_dupeclass_allowlist.txt, tools/python_interpreter/BUILD, tools/python_interpreter/README.md, tools/python_interpreter/check_python_path.py, tools/springboot/BUILD, tools/springboot/README.md, tools/springboot/check_dupe_classes.py, tools/springboot/springboot.bzl, tools/springboot/tests/check_dupe_classes_test.py
Mainly, this PR improves the Spring Boot rule in that it will use the captive Python3 toolchain in Bazel (if one is configured), rather than system python. This is good because for hermetic builds, as we don't want to rely on system Python.
Details of the changes:
1. the dupe class checker python script is now called directly from Starlark instead of a genrule
2. the rule will now use python from the toolchain if it is configured
3. we now short circuit the invocation before invoking the python script if fail_on_duplicate_classes = False
4. the output file from the rule invocation will now contain the full description of the errors, if the invocation fails
Fixes issue #44
=> use captive python instead of system python, and other improvements

samples/helloworld/BUILD, tools/springboot/README.md, tools/springboot/springboot.bzl
Instead of reiterating the deps in the springboot rule, this PR allows the deps to be stated once in the java_library, and pulled through in the springboot rule. Fixes issue #31 .
**PREVIOUS:**
```
java_library(
name = "helloworld_lib",
srcs = glob(["src/main/java/**/*.java"]),
resources = glob(["src/main/resources/**"]),
deps = springboot_deps + lib_deps,
)
springboot(
name = "helloworld",
boot_app_class = "com.sample.SampleMain",
java_library = ":helloworld_lib",
deps = springboot_deps + lib_deps,
)
```
**NEW:**
```
java_library(
name = "helloworld_lib",
srcs = glob(["src/main/java/**/*.java"]),
resources = glob(["src/main/resources/**"]),
deps = springboot_deps + lib_deps,
)
springboot(
name = "helloworld",
boot_app_class = "com.sample.SampleMain",
java_library = ":helloworld_lib",
) …
```
=> pull through deps from the java_library

samples/helloworld/BUILD, tools/springboot/README.md, tools/springboot/springboot.bzl
This PR adds support for customization of launches using **bazel run**:
**JVM Args**
Defining JVM args for a spring boot application in the BUILD file   (Issue #36)
```
springboot(
name = "helloworld",
boot_app_class = "com.sample.SampleMain",
java_library = ":helloworld_lib",
jvm_flags = "-Dcustomprop=gold",
)
```
**Main Args**
Are now passed onto the Spring Boot application (Issue #8)
```
bazel run //samples/helloworld red green blue
```
=> support args for bazel run invocations

samples/helloworld/BUILD, samples/helloworld/helloworld_classpath.idx, samples/helloworld/src/main/java/com/sample/SampleMain.java, tools/springboot/BUILD, tools/springboot/springboot.bzl, tools/springboot/springboot_pkg.sh
This implements the solution for #33 for classpath.idx files. This is a new feature in Spring Boot 2.3.
https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-executable-jar-format.html#executable-jar-war-index-files-classpath
This PR allows you to pass in a classpath.idx file, which will be positioned inside the Spring Boot executable jar file.
```
springboot(
name = "helloworld",
boot_app_class = "com.sample.SampleMain",
java_library = ":helloworld_lib",
classpath_index = "helloworld_classpath.idx",
)
```
=> implement support for classpath.idx file

samples/helloworld/BUILD, tools/springboot/README.md, tools/springboot/springboot.bzl, tools/springboot/unwanted_classes.md
Docs for issue #33, consolidated in a new doc unwanted.md with the exclude list, and dupe class checker.
Also introduced a minor simplification for the dupe class checker allowlist - the passed value can now be a file, which simplifies the usage.
=> document classpath index feature

samples/helloworld/remote_debug.sh, tools/springboot/springboot_pkg.sh
pushd and popd have been writing useless lines into the build log, finally got around to tracking it down and fixing it
=> remove two verbose log lines from springboot rule execution

examples/helloworld/BUILD, examples/helloworld/custom_launcher_script.sh, examples/helloworld/src/main/java/com/sample/SampleAutoConfiguration.java, springboot/BUILD, springboot/README.md, springboot/default_launcher_script.sh, springboot/springboot.bzl, springboot/write_gitinfo_properties.sh, springboot/write_launcherenv.sh, springboot/write_manifest.sh
This provides a way for the user to replace the launcher script used when invoking the Spring Boot application via 'bazel run' #92 
There were some gymnastics involved, as there are some variables that need to be substituted in the launcher script. I implemented this by generating an extra env script that provides those values that gets invoked prior to invoking the actual launcher script.
=> add launcher_script attribute to springboot rule so user can provide script for bazel run

examples/README.md
I created a kotlin springboot example. I didn't want to add in Kotlin in our primary WORKSPACE since most users will not use it. So I put it in a separate branch in this repo. This fixes #84
=> add link to the kotlin example

springboot/write_manifest.sh
This PR addresses #111. 
The Bash script `write_manifest.sh` extracts the from the file name of the Spring boot dependencies, which is not a reliable source. This PR extracts it from the MANIFEST of a Spring Boot dependency.
This is not super reliable either, maybe we could search all dependencies for `Automatic-Module-Name: spring.boot.starter...` and use this?
Could this fix also be applied to a 2.0.0 branch and released as 2.0.1?
=> Extract Spring-Boot-Version from the MANIFEST of a Spring Boot JAR

springboot/README.md, springboot/check_dupe_classes.py, springboot/springboot.bzl, springboot/springboot_doc.md
Completes the attribute renames. The rule still honors the old names, so backwards compatibility is maintained. This is for Issue #79.
The new names show consistency in naming, based on the feature area where they apply. *deps_\** control dependencies, *bazelrun_\** control bazel run behavior, and *dupclassescheck_** control the duplicate class validator.
Renamed attributes:
- exclude => deps_exclude
- classpath_index => deps_index_file
- use_build_dependency_order => deps_use_starlark_order
- fail_on_duplicate_classes => dupeclassescheck_enable
- duplicate_class_allowlist => dupeclassescheck_ignorelist
- jvm_flags => bazelrun_jvm_flags
- data => bazelrun_data
=> make attribute names more consistent and clear

springboot/write_manifest.sh
Another instance of #119 where we fail if a system level java is not installed. Found by using this rule on a new laptop with no system Java installed.
=> fix another javabase bug

examples/demoapp/src/main/java/com/sample/SampleMain.java, springboot/bazelrun.md
We had a question internally about passing args to bazel run, which we didn't have doc'd. Also, a special case of args that start with -- needed to be covered.
=> improve docs for args to bazel run

springboot/BUILD, springboot/README.md, springboot/cli.md, springboot/src/main/java/com/salesforce/rulesspring/cli/SpringBootInspector.java, springboot/src/main/java/com/salesforce/rulesspring/index/IndexFileType.java, springboot/src/main/java/com/salesforce/rulesspring/index/IndexOfFiles.java, springboot/src/main/java/com/salesforce/rulesspring/index/IndexedFile.java, springboot/src/main/java/com/salesforce/rulesspring/index/SpringBootIndexReporter.java, springboot/src/main/java/com/salesforce/rulesspring/index/SpringBootJarIndexer.java, springboot/src/test/java/com/salesforce/rulesspring/index/SpringBootJarIndexerTest.java
While working on an issue today, wanted a better way to slice and dice the contents of the problematic Spring Boot app. Ended up writing a simple indexer CLI. This code locastion will serve eventually as the location of the reimplementation of the _springboot_ rule in Java (see #3) . For now it is just a single operation CLI.
=> first drop of the springboot CLI

springboot/springboot.bzl, springboot/springboot_doc.md, springboot/springboot_pkg.sh
https://github.com/salesforce/rules_spring/issues/163
Sometimes people don't want to include the git.properties in the jar they will deploy (security etc).
Providing mechanism to not include git.properties file in the resulting jar e.g.
```
springboot(
name = "abc",
boot_app_class = "x.y.z",
include_git_properties_file = False,
java_library = ":abc",
)
```
The above target results in the following behaviour:
```
jar tf bazel-bin/projects/something/abc.jar | grep git.properties
<whole lot of nothing>
```
Also generated new Stardocs (this is cool, never saw it before).
=> provide mechanism to not include git.properties file in resulting jar

springboot/default_bazelrun_script.sh, springboot/springboot.bzl, springboot/springboot_doc.md
Solves #16 effectively. It allows the caller to pass in the label to a java toolchain into the springboot macro. Then, when the user launches the service with bazel run, the JVM will be launched from the toolchain.
Also added support for BAZEL_RUN_JAVA environment variable that will be used before any other options.
=> add bazelrun_java_toolchain attribute to launch service with the java toolchain JVM

springboot/bazelrun.md, springboot/default_bazelrun_script.sh, springboot/springboot.bzl
Iterating on the solution for #16 
Now the default is the current workspace toolchain, instead of JAVA_HOME.
=> improve default behavior of bazel run jvm

springboot/springboot.bzl, springboot/springboot_pkg.sh, springboot/write_manifest.sh
Attempt at fixing https://github.com/salesforce/rules_spring/issues/177
Works in our project, and has backward compatability.
Open to suggestions for improvements!
=> Add support for passing new Spring Boot JarLauncher class

examples/demoapp/BUILD, examples/demoapp/src/main/java/com/sample/SampleMain.java, examples/demoapp/src_root/main/java/com/sample/SampleRootClass.java, springboot/springboot_pkg.sh
This feature is a simple partial solution to #129 . It is for cases where a service needs to inject more classes into the root of the executable jar. This means the classes are written directly into the root of the jar, not in *BOOT-INF/classes* or *BOOT-INF/libs*.
It works by creating a *java_library* target with the special name: **rootclassloader_lib**
```
java_library(
name = "rootclassloader_lib",
srcs = glob(["src_root/main/java/**/*.java"]),
)
```
then adding the *java_library* to the deps attribute of the *springboot* rule:
```
springboot(
name = "demoapp",
boot_app_class = "com.sample.SampleMain",
java_library = ":demoapp_lib",
deps = [ ":rootclassloader_lib", ],
...
```
I am not comfortable making this an official feature since it is a bit hacky, using a naming convention. But …
=> Add root classloader support for custom classes

springboot/write_manifest.sh
This pull request updates write_manifest.sh to use awk instead of rev to fix "rev: command not found" when executing on Windows (fixes #200).
=> Replace rev with awk to fix "rev: command not found" on Windows

springboot/springboot.bzl
This pull request fixes the springboot rule to search for either `bin/java` or `bin/java.exe` (fixes #198).
=> Fix the springboot rule failing on Windows with "Error: index out of range (index is 0, but sequence has 0 elements)"

springboot/README.md
It looks like it's copied from a location within the `@rules_spring` repository where that wouldn't have been required.
=> fix: example needs absolute label syntax

springboot/springboot_pkg.sh
Invoke singlejar with a relative path to the output JAR, preventing the build-data.properties file from containing the absolute path.
Fixes: #205
=> #205 Fix non-determinism in build-data.properties file

springboot/springboot.bzl, springboot/springboot_doc.md
Default should be fine for 99.9% of use cases. But if you are a large corp, you are probably lucky and have a .1% use case.
Solves #209
=> add jartools_toolchains attribute

makerelease.sh
Reduces the amount of cruft in the release zip file.
Fixes #212
=> cleanup the makerelease script

examples/demoapp/BUILD, examples/demoapp/demoapp_dupeclass_allowlist.txt, springboot/deps_filter_transitive.bzl, springboot/unwanted_classes.md
This is an improved mechanism for excluding dependencies. Credit and thanks to @MohitBhar.
This mechanism allows your tests to run with the classpath used by the executable jar. The deps_exclude mechanism did not provide this.
Solution for #171
=> Add the deps filter mechanism and update docs and examples.

springboot/springboot.bzl
Currently, the springboot rule does not forward attributes `restricted to` and `target_compatible_with`  to the created rules.
With configurations that depend on these rules to determine compatibility, this can pose an issue. 
Forwarded attributes to custom rules
=> Forward restricted_to and target_compatible_with attributes to rules

springboot/springboot.bzl
@bhnord I found the default for _restricted_to_ needs to be _None_, not _[]_ despite their documentation here:
```
restricted_to  List of labels;  nonconfigurable; default is []
```
https://bazel.build/reference/be/common-definitions
I was getting build errors for the examples with _[]_
=> fix default for restricted_to

MODULE.bazel
Fixes CI failure due to:
```
Error in fail: The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.
```
Solution described by https://github.com/bazelbuild/rules_python/issues/1169
=> fix python bzlmod issue

springboot/springboot.bzl
ibazel was failing to run this script because of the newline before the shebang. Strangely, `bazel run` worked fine, but `file <script>` also cares about the newline so I don't think this is really an ibazel bug.
Fixes #143
=> Fix shebang in bazelrun wrapper

MODULE.bazel, examples/README.md
Have built a proper, publicly facing, external test app, and discovered an issue in the module metadata.
Formerly, I would use our internal monorepo for testing. But it isn't on Bzlmod yet, so I was hindered in testing.
=> fix module metadata

README.md, springboot/README.md, springboot/springboot_doc.md
Improved our docs for attributes, and added some doc links for the [SpringBoot3 upgrade Issue](https://github.com/salesforce/rules_spring/issues/230) I created.
It finally closes out #78 by providing a simple example.
We ended up not doing that in our monorepo for years, until today.
=> enhance docs for attributes

springboot/default_bazelrun_script.sh, springboot/springboot.bzl, springboot/write_bazelrun_env.sh
Two updates:
- New attribute *bazelrun_jvm_flag_list* is the new form of *bazelrun_jvm_flags* but is more bazel-like: it is an array of JVM args, instead of a space separated string
- Discovered that ADD_OPENS and ADD_EXPORTS bazel run script variables were not working correctly in some cases. There was no delineation between them and JVM_FLAGS and so in some cases jvm flags were being processed as ADDs. Removed those two variables since ADDs can just be treated as additional JVM_FLAGS in a single list.
=> fix bazelrun jvmflags, add list attribute

examples/demoapp/BUILD, examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java, examples/demoapp/src/main/resources/META-INF/spring.factories, examples/demoapp/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, examples/helloworld/src/main/resources/META-INF/spring.factories, examples/helloworld/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Updates for the demos:
- fixed auto configs (missed in the earlier Boot3 upgrade)
- added more bazel run jvm flags to the demoapp
=> demo updates: fix autoconfigs, add jvmflags for bazel run

examples/demoapp/BUILD, examples/demoapp/application-dev.properties, examples/demoapp/application.properties, examples/demoapp/config/application.properties, examples/demoapp/custom_bazelrun_script.sh, examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java, examples/demoapp/src/main/resources/application.properties, springboot/bazelrun.md, springboot/default_bazelrun_script.sh, springboot/springboot.bzl, springboot/springboot_doc.md, springboot/write_bazelrun_env.sh
Clarifies support for data files in the bazel run launcher script.
Additionally, the launcher script will now detect application.properties files and configure them as external configuration files for Spring Boot.
Solves #135
=> support external application.properties files for bazel run

examples/demoapp/BUILD, examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java, springboot/bazelrun.md, springboot/springboot.bzl, springboot/write_bazelrun_env.sh
Allows the springboot() invocation to specify environment variables that will be loaded into the bazel run launcher script. These could be used to set individual spring properties.
```
bazelrun_env_flag_list = ["PROP1=blue", "PROP2=green"],
```
Solves #166
=> support bazel run env variables

springboot/default_bazelrun_script.sh
Fixes direct invocation of the bazel run wrapper script.
```
bazel run //examples/helloworld
./bazel-bin/examples/helloworld/helloworld
```
Solves #110.
=> support direct invocation of bazel run wrapper script

.bazelrc
The examples are Java, and are compiled using the settings .bazelrc. Set the settings explicitly to 17.
=> pin examples to JDK17

examples/demoapp/BUILD, examples/demoapp/README.md, examples/demoapp/generate-build-info.bzl, examples/demoapp/generate-build-info.sh, examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java
Provides a working example of using Spring's BuildProperties bean. Thanks @MohitBhar for creating the internal version of this, that I extracted into this example.
Run:
```bash
bazel run --action_env=BUILD_NUMBER=998 --action_env=BUILD_TAG=green examples/demoapp  
```
and then check:
```
http://localhost:8080/actuator/info
```
vscode/ij reordered the BUILD file, unfortunately.
=> add example for BuildProperties

examples/demoapp/BUILD, examples/demoapp/src/test/java/com/salesforce/rules_spring/PackagingTest.java, springboot/springboot.bzl, springboot/springboot_pkg.sh
Fixes bug where git.properties was renamed, and unavailable, due to multi-target support implemented in #139.
Fix for #259.
This PR fixes the issue, and adds packaging tests to prevent future issues.
IJ reformatted some files.
=> fix git.properties

springboot/deps_filter_transitive.bzl
We moved this filter, but it has been in a few releases so we need to deprecate it instead.
It prints a warning when used.
=> add back deps_filter_transitive for back compat
